### PR TITLE
updated content

### PR DESCRIPTION
**Pull request by JoshuaUrrutia**
Updated the content for the `intro_to_hpc`, `gnu_utils`, and `intro_to_linux` sections. Still need to restructure/delete things to fit these sections into the new schedule.

### CODE REVIEW

**Comment by JoshuaUrrutia** [comment]
Please look over solutions in `Introduction to High Performance Computing II: Command Line Utilities` section specifically.

Tree command isn't on Stampede2

There is some redundancy with cat, less, more, grep appearing in both `intro_to_linux_04.md` and `gnu_utils_02.md` sections. But the second section includes flags, and I think it's better to revisit those commands in the second section rather than removing them from one section.

**Comment by wjallen** [comment]
Quick comment on command redundancy: We decided to leave some of those commands in twice to reinforce learning. We went pretty quickly over them the first time around, and went a little more in depth with more examples of flags the second time around

**Comment by zyndagj** [comment]
Text looked good. I'll test samples next.

**Comment by wjallen** [comment]
I read over everything and tested examples. Sent Josh a few comments directly in slack. looks good

**Pull request merged**
